// <auto-generated />
using System;
using Coreweb_api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Coreweb_api_token.Migrations
{
    [DbContext(typeof(StudDataContext))]
    [Migration("20220706095335_studtoken")]
    partial class studtoken
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Coreweb_api_token.Model.Student", b =>
                {
                    b.Property<int>("Stuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Stuid"), 1L, 1);

                    b.Property<int>("Sage")
                        .HasColumnType("int");

                    b.Property<string>("Sfname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("slname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Stuid");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Coreweb_api_token.Model.Userinfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("userinfos");
                });
#pragma warning restore 612, 618
        }
    }
}
